version: '3.8'

services:
  mysql:
    image: mysql:8.0
    command: --log-error-verbosity=2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passroot
      MYSQL_USER: msqluser
      MYSQL_PASSWORD: msqlpass
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 5

  app:
    depends_on:
      mysql:
        condition: service_healthy
    build: .
    tty: true

volumes:
  mysql_data: